import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { directoryFixture, implemented } from './helpers.mjs';
import { inspectNote, checkNotes } from '../scripts/lib/notes.mjs';
const filename='.agents/notes/2026-09-28-output.md';
test('valid implemented note passes actual format checker',t=>{const f=directoryFixture(t);f.write(filename,implemented);assert.deepEqual(checkNotes(f.repo),{checked:1,errors:[]});});
test('missing alternatives is rejected',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented.replace('## Alternatives considered','## Other'),filename,f.repo).some(s=>s.includes('Alternatives')));});
test('fenced headings cannot counterfeit required sections',t=>{const f=directoryFixture(t);const x=implemented.replace('## Alternatives considered','```md\n## Alternatives considered\n```');assert.ok(inspectNote(x,filename,f.repo).some(s=>s.includes('Alternatives')));});
test('implemented note cannot retain proposal headings',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented+'\n## Proposal\nLater.\n',filename,f.repo).some(s=>s.includes('cannot')));});
test('duplicate status is rejected',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented+'\nStatus: proposed\n',filename,f.repo).some(s=>s.includes('Status')));});
test('empty required section is rejected',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented.replace('Legacy consumers require text output.',''),filename,f.repo).some(s=>s.includes('Empty')));});
test('unmarked existing ADR is left to its own conventions',t=>{const f=directoryFixture(t);f.write(filename,'# An existing ADR\nNo plugin headings.');assert.deepEqual(checkNotes(f.repo),{checked:0,errors:[]});});
test('invalid local link is rejected',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented+'\n[code](missing.js)\n',filename,f.repo).some(s=>s.includes('link')));});
test('existing local link resolves relative to the note',t=>{const f=directoryFixture(t);assert.deepEqual(inspectNote(implemented+'\n[code](../../app.js)\n',filename,f.repo),[]);});
test('escaping local link is rejected',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented+'\n[secret](../../../secret)\n',filename,f.repo).some(s=>s.includes('link')));});
test('external URLs are not fetched',t=>{const f=directoryFixture(t);assert.deepEqual(inspectNote(implemented+'\n[external](https://example.invalid/no-network)\n',filename,f.repo),[]);});
test('invalid calendar date is rejected',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented,'.agents/notes/2026-02-31-topic.md',f.repo).some(s=>s.includes('YYYY')));});
test('superseded record requires replacement link',t=>{const f=directoryFixture(t);assert.ok(inspectNote(implemented.replace('Status: implemented','Status: superseded')+'\n## Superseded by\nSome later design.\n',filename,f.repo).some(s=>s.includes('replacement')));});
test('archived subtree is not modernized or format-checked',t=>{const f=directoryFixture(t);f.write('.agents/notes/archived/old.md','<!-- repo-knowledge:decision -->\nOld.');assert.deepEqual(checkNotes(f.repo),{checked:0,errors:[]});});
test('no notes directory is a valid no-op',t=>{const f=directoryFixture(t);assert.deepEqual(checkNotes(f.repo),{checked:0,errors:[]});assert.ok(!fs.existsSync(path.join(f.repo,'.agents')));});
test('notes scan refuses a symlink into outside content',t=>{const f=directoryFixture(t);f.write(filename,implemented);fs.symlinkSync(path.join(f.repo,'app.js'),path.join(f.repo,'.agents/notes/evil.md'));assert.throws(()=>checkNotes(f.repo),/symlink/i);});
